name: Node Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    paths: [ "node/**"]

jobs:
  build-image-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build image
        run: docker build -t node:test ./node
      - 
        name: Check version
        run: |
          docker run --rm node:test bash -c "node -v"

  build-image-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./node
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node:${{ github.ref_name }}
