name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    paths: [ "rust/**"]

jobs:
  build-image-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build image
        run: docker build -t rust-build:test ./rust
      - 
        name: Run test inside container
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work rust-build:test \
            bash -c "cargo new test_project && cd test_project && cargo run"

  build-image-publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./rust
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rust-build:${{ github.ref_name }}
